#ifndef PORT_PINMODE_CFG_H
#define PORT_PINMODE_CFG_H

#include "Port_Types.h"

#define PORT_PIN_AFMODE_TIM2_CH1 PORT_PIN_A0
#define PORT_PIN_AFMODE_TIM2_CH2 PORT_PIN_A1
#define PORT_PIN_AFMODE_TIM2_CH3 PORT_PIN_A2
#define PORT_PIN_AFMODE_TIM2_CH4 PORT_PIN_A3

#define PORT_PIN_AFMODE_TIM1_CH1 PORT_PIN_A8
#define PORT_PIN_AFMODE_TIM1_CH2 PORT_PIN_A9
#define PORT_PIN_AFMODE_TIM1_CH3 PORT_PIN_A10
#define PORT_PIN_AFMODE_TIM1_CH4 PORT_PIN_A11

#define PORT_PIN_AFMODE_SPI1_NSS PORT_PIN_A4
#define PORT_PIN_AFMODE_SPI1_SCK PORT_PIN_A5
#define PORT_PIN_AFMODE_SPI1_MISO PORT_PIN_A6
#define PORT_PIN_AFMODE_SPI1_MOSI PORT_PIN_A7

#define PORT_PIN_AFMODE_SPI2_NSS PORT_PIN_B12
#define PORT_PIN_AFMODE_SPI2_SCK PORT_PIN_B13
#define PORT_PIN_AFMODE_SPI2_MISO PORT_PIN_B14
#define PORT_PIN_AFMODE_SPI2_MOSI PORT_PIN_B15

#endif /* PORT_PINMODE_CFG_H */
