#include "Timer_PinMap_Cfg.h"

/*
 * Selected project routing.
 *
 * This table is OPTIONAL.
 * It is useful when the Timer MCAL needs to validate that the
 * configured Timer Channel and Port Pin form a legal combination.
 *
 * For a simple implementation, the #define map in
 * Timer_PinMap_Cfg.h may be sufficient.
 */

const Timer_PinMapType Timer_PinMap_Config[] =
{
    { TIMER_CHANNEL_TIM1_CH1, TIMER_PIN_TIM1_CH1_DEFAULT,  TIMER_REMAP_NONE },
    { TIMER_CHANNEL_TIM1_CH2, TIMER_PIN_TIM1_CH2_DEFAULT,  TIMER_REMAP_NONE },
    { TIMER_CHANNEL_TIM1_CH3, TIMER_PIN_TIM1_CH3_DEFAULT,  TIMER_REMAP_NONE },
    { TIMER_CHANNEL_TIM1_CH4, TIMER_PIN_TIM1_CH4_DEFAULT,  TIMER_REMAP_NONE },

    { TIMER_CHANNEL_TIM2_CH1, TIMER_PIN_TIM2_CH1_DEFAULT,  TIMER_REMAP_NONE },
    { TIMER_CHANNEL_TIM2_CH2, TIMER_PIN_TIM2_CH2_DEFAULT,  TIMER_REMAP_NONE },
    { TIMER_CHANNEL_TIM2_CH3, TIMER_PIN_TIM2_CH3_DEFAULT,  TIMER_REMAP_NONE },
    { TIMER_CHANNEL_TIM2_CH4, TIMER_PIN_TIM2_CH4_DEFAULT,  TIMER_REMAP_NONE },

    { TIMER_CHANNEL_TIM3_CH1, TIMER_PIN_TIM3_CH1_DEFAULT,  TIMER_REMAP_NONE },
    { TIMER_CHANNEL_TIM3_CH2, TIMER_PIN_TIM3_CH2_DEFAULT,  TIMER_REMAP_NONE },
    { TIMER_CHANNEL_TIM3_CH3, TIMER_PIN_TIM3_CH3_DEFAULT,  TIMER_REMAP_NONE },
    { TIMER_CHANNEL_TIM3_CH4, TIMER_PIN_TIM3_CH4_DEFAULT,  TIMER_REMAP_NONE },

    { TIMER_CHANNEL_TIM4_CH1, TIMER_PIN_TIM4_CH1_DEFAULT,  TIMER_REMAP_NONE },
    { TIMER_CHANNEL_TIM4_CH2, TIMER_PIN_TIM4_CH2_DEFAULT,  TIMER_REMAP_NONE },
    { TIMER_CHANNEL_TIM4_CH3, TIMER_PIN_TIM4_CH3_DEFAULT,  TIMER_REMAP_NONE },
    { TIMER_CHANNEL_TIM4_CH4, TIMER_PIN_TIM4_CH4_DEFAULT,  TIMER_REMAP_NONE }
};

const uint32 Timer_PinMap_ConfigCount =
    (uint32)(sizeof(Timer_PinMap_Config) / sizeof(Timer_PinMap_Config[0]));
